name: SHR
on:
  push:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6.1.0
        with:
          node-version: 20
      - name: caching
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: linting
        run: npm run lint
      - name: unit test
        run: npm run test
      - name: building
        run: npm run build
