name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node.js dependencies
        id: cache-node
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ruzake
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/ryuzake/react-app-cicd:${{ github.sha }}
            ghcr.io/ryuzake/react-app-cicd:latest

  CD:
    runs-on: ec2
    needs: CI
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ruzake
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/ruzake/react-app-cicd:${{ github.sha }}

      - name: Stop Old Container (if running)
        run: |
          docker stop react-app || true
          docker rm react-app || true

      - name: Run Docker Container
        run: |
          docker run -d \
            --name react-app \
            -p 80:80 \
            ghcr.io/ruzake/react-app-cicd:${{ github.sha }}

      - name: Verify App is Running
        run: |
          sleep 5
          curl -f http://localhost:80 || exit 1
